name: client
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^16.3.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^3.0.3
  dio: ^5.9.0
  retrofit: ^4.8.0
  retrofit_generator: ^10.0.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  custom_lint: ^0.8.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1
  dotted_border: ^3.1.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/categories/
    - assets/icons/type/
    - assets/image/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
